version: '3.2'
services:
  contaloupe:
    container_name: cantaloupe
    image: lyrasis/cantaloupe:latest
    ports:
      - "8182:8182"
    environment:
        SOURCE_STATIC: "HttpSource"
        HTTPSOURCE_BASICLOOKUPSTRATEGY_URL_PREFIX: "http://host.docker.internal/ndar_image_cache/"
        HTTPSOURCE_BASICLOOKUPSTRATEGY_URL_SUFFIX: ".jpg"
        ENDPOINT_ADMIN_ENABLED: "true"
        ENDPOINT_ADMIN_USERNAME: "admin"
        ENDPOINT_ADMIN_SECRET: "kinexis"
        PRINT_STACK_TRACE_ON_ERROR_PAGES: "false"
        ENDPOINT_IIIF_1_ENABLED: "false"
        ENDPOINT_IIIF_2_ENABLED: "true"
        ENDPOINT_API_ENABLED: "false"
        CACHE_SERVER_WORKER_INTERVAL: "3600"
        CACHE_SERVER_SOURCE_ENABLED: "true"
        CACHE_SERVER_DERIVATIVE_ENABLED: "true"
        CACHE_SERVER_DERIVATIVE: "FilesystemCache"
        JAVA_OPTS: "-Xmx2g"
        PROCESSOR_JP2: "OpenJpegProcessor"
    restart: always